export default function Head() {
  return (
    <>
      <title>Thankful Thoughts</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <script
        async
        defer
        data-website-id="a2feaec7-b0c5-4089-9733-0f257e29309d"
        src="https://hosnaqasmei-umami.vercel.app/umami.js"
      ></script>
      <link
        rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🙏</text></svg>"
      />
    </>
  )
}
